# Generated by Django 6.0 on 2025-12-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
